
---
title: "Debug Note"
date: now
author: "Yuta & Aaron"
description: "<BR>This documents the debugging history."
title-block-banner: true
format:
  html:
    theme: 
      light: flatly
      dark: darkly    
    fontsize: 1.0em
    self-contained: true
    toc: true
    toc-location: left
    number-sections: true
    number-depth: 3
    code-fold: true
    grid:
      sidebar-width: 200px
      body-width: 1000px
      margin-width: 200px
      gutter-width: 2.5rem
execute:
  warning: false
editor: 
  markdown: 
    wrap: 72
---

## First Time Create Environment in the terminal
```{bash}
conda env create --file environment.yml
```

```{bash}
conda env list
conda init
```

close terminal and reopen

## Verify install by running the following command in the terminal
```{bash}
conda activate py39
conda list
python
```

```{python}
import os
import sys

print('getcwd:      ', os.getcwd())
sys.path.append(os.getcwd())
sys.path.append(os.getcwd()+'/src/analysis')

# from src.analysis import analysisOrbit
import analysisOrbit
from astropy import units as u

analysisRocket = analysisOrbit.hohmanTransfer(orbit_init=400, orbit_target=36000)
# analysisRocket = analysisOrbit.hohmanTransfer(orbit_init=r.initOrbit, orbit_target=r.targetOrbit, m_init=r.m_dry, I_sp=r.I_sp)
# analysisRocket = analysisOrbit.hohmanTransfer(orbit_init=400, orbit_target=35786, m_init=5000, I_sp=300)

total_delta_v = analysisRocket.calculate_delta_v()


print(f"Total delta-v: {total_delta_v}")

```

this code works!
next we verify the quarto executions.


## Using Quarto

```{r}
1+1

install.packages("reticulate")

```

```{r}
library(reticulate)

use_condaenv("py39")

```

```{r}
reticulate::py_config()
reticulate::use_python("/opt/conda/envs/py39/bin/python")
```
python:         /opt/conda/envs/py39/bin/python


In python interpreter,

>>> import sys
>>> 
>>> print(sys.executable)
/opt/conda/envs/py39/bin/python

```{python}
import sys

print(sys.executable)
```

```{python}
import os
import sys

print('getcwd:      ', os.getcwd())
sys.path.append(os.getcwd())
sys.path.append(os.getcwd()+'/src/analysis')

from astropy import units as u
from poliastro.bodies import Earth
from poliastro.twobody import Orbit

```

error logs

```
Traceback (most recent call last):
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/llvmlite/binding/ffi.py", line 136, in __getattr__
    return self._fntab[name]
KeyError: 'LLVMPY_AddSymbol'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/llvmlite/binding/ffi.py", line 117, in _load_lib
    self._lib_handle = ctypes.CDLL(str(lib_path))
  File "/opt/conda/envs/py39/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /opt/conda/envs/py39/lib/python3.9/site-packages/llvmlite/binding/libllvmlite.so)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/vscode/R/x86_64-pc-linux-gnu-library/4.3/reticulate/python/rpytools/loader.py", line 122, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/home/vscode/R/x86_64-pc-linux-gnu-library/4.3/reticulate/python/rpytools/loader.py", line 96, in _run_hook
    module = hook()
  File "/home/vscode/R/x86_64-pc-linux-gnu-library/4.3/reticulate/python/rpytools/loader.py", line 120, in _hook
    return _find_and_load(name, import_)
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/poliastro/twobody/__init__.py", line 1, in <module>
    from poliastro.twobody.orbit import Orbit
  File "/home/vscode/R/x86_64-pc-linux-gnu-library/4.3/reticulate/python/rpytools/loader.py", line 122, in _find_and_load_hook
    return _run_hook(name, _hook)
  F
```


# For R


```r
install.packages("reactable", repos='http://cran.us.r-project.org')
install.packages("igraph")
install.packages("libmkl-rt")
install.packages("libglpk40")
install.packages("networkD3")
install.packages("reticulate")
install.packages("tidyverse")
install.packages("collapsibleTree")
install.packages("colorspace")
install.packages("jsonlite")
install.packages("DT")
install.packages("devtools")
library(devtools)

install_github("UTNAK/tansakusuR")
install_github("UTNAK/omlhashiR")
```


## Install libglpk40 package in the terminal
```{bash}
sudo apt-get update
sudo apt install -y libglpk40
```

## Install dependencies in environment.yml by running this command in the terminal
```bash
conda env update --file environment.yml --prune
```



# Troubleshooting
## Start and activate conda environment in a terminal (debugging purposes only)
```{markdown}
conda create -y -n py39 python=3.9
conda init
<!-- Close and reopen the terminal -->
conda activate py39
```

